#!/bin/bash
#http://askubuntu.com/questions/66914/how-to-change-desktop-background-from-command-line-in-unity

if [[ $1 == '' ]]; then
    echo 'Must specify a directory'
    exit
fi
PID=$(pgrep gnome-session)
#http://askubuntu.com/questions/140305/cron-not-able-to-succesfully-change-background#answer-368370
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
PIC=$(ls $1/* | shuf -n1)
/usr/bin/gsettings set org.gnome.desktop.background picture-uri "file://$PIC" > /tmp/gsett 2>&1
echo $PIC
