#!/usr/bin/env python3
# maybe use googler !
import sys
import requests
# var = requests.get(f'http://www.google.com/search?q="{sys.argv[1]}"&btnI')
# print(var.url)
var = requests.get(f'http://www.google.com/search?q="{" ".join(sys.argv[1:])} site:youtube.com"&btnI')
print(var)
import IPython; IPython.embed()
