#!/usr/bin/env python3
import sys
import requests
# var = requests.get(f'http://www.google.com/search?q="{sys.argv[1]}"&btnI')
# print(var.url)
# import IPython; IPython.embed()
var = requests.head(f'http://www.google.com/search?q="{" ".join(sys.argv[1:])} site:youtube.com"&btnI')
print(var.headers["Location"])
