#!/usr/bin/python

import os, sys, random

if __name__ == "__main__":
        #if len(sys.argv) < 2:
        #        print "Pass folder path as argument"
        #        sys.exit(1)
        cwd = os.getcwd()
        files = os.listdir(cwd)
        n = random.randint(0,len(files)-1)
	target = os.path.join(cwd,files[n])
	cmd = "gnome-open \""+target+"\""
	print target

