#!/usr/bin/env python3
import sys
import os
from pathlib import Path
def set_tmp(tmp):
    # os.system(f"sct {new_tmp}")
    os.system(f"redshift -O {new_tmp}")

a = sys.argv
p = (Path("/") / "tmp" / 'current_tmp')
if len(a) == 1:
    print("Usage: ")
    print("    sct1 TEMP")
    print("    sct1 +TEMP")
    print("    sct1 -TEMP")
if len(a) == 2:
    tmp = sys.argv[1]
    new_tmp = min(max(1_000, int(tmp)), 10_000)
    if tmp[0] in ('-', '+'):
        if p.exists():
            current = int(p.read_text())
            amount = int(tmp[0] + tmp[1:])
            new_tmp = min(max(1_000, current + amount), 10_000)
            # print(f"sct {new_tmp}")
            set_tmp(new_tmp)
        else:
            # print(f"{p} doesnt exist")
            pass
    else:
        set_tmp(new_tmp)
    # print(str(new_tmp))
    p.write_text(str(new_tmp))

