#!/bin/bash

#sudo python2 /usr/local/bin/smbserver.py -comment 'My share' PUBLIC ~/Public
#sudo docker run -it -p 139:139 -p 445:445 -v /tmp:/exports dperson/samba -s "public;/exports;yes;no;yes;all;all"
docker run --rm -it -p 137:137/udp \
    -p 138:138/udp -p 139:139 -p 445:445 \
    -v $HOME/Public:/exports:rw dperson/samba bash \
    -c 'chmod 7777 /exports&& ./usr/bin/samba.sh -n -S -s "public;/exports;yes;no;yes;all;all"'
#sudo docker run -it -p 139:139 -p 445:445 -v /tmp:/exports dperson/samba -s "public;/exports;yes;no;no;foo;foo" -u "foo;bar"
