#!/usr/bin/env node
// Basado en https://codepen.io/mrmlnc/full/GqrqPg
var fs = require('fs');
var data = fs.readFileSync(0, 'utf-8');
process.stdout.write(getSnippet(data) + "\n"); // prompt for next

function getMostUsed(a) { var b = 0, c = 0, d = 0; for (var e in a) { var f = a[e], g = f[0], h = f[1]; (g > c || g === c && h > d) && (c = g, d = h, b = Number(e)) } return b } function getIndent(a) { if ("string" != typeof a) throw new TypeError("Expected a string"); var f, g, b = 0, c = 0, d = 0, e = {}; a.split(/\n/g).forEach(function (a) { if (a) { var h, i = a.match(INDENT_RE); i ? (h = i[0].length, i[1] ? c++ : b++) : h = 0; var j = h - d; d = h, j ? (g = j > 0, f = e[g ? j : -j], f ? f[0]++ : f = e[j] = [1, 0]) : f && (f[1] += Number(g)) } }); var i, h = getMostUsed(e); return h ? i = c >= b ? "space" : "tab" : (i = null), { amount: h, type: i } } var INDENT_RE = /^(?:( )+|\t+)/;

// Source @ Sindre Sorhus: https://github.com/sindresorhus/repeating
function repeating(a, b) { var c = ""; do 1 & a && (c += b), b += b; while (a >>= 1); return c }

function getSnippet(txt) {
    let lines = txt.split("\n");
  // Naive monkey 🙉
  let indentAmount = 100;
  let indentType = '	';

  for (let i = 0; i < lines.length; i++) {
    const lineIndent = getIndent(lines[i]);
    if (lineIndent.type === 'space') {
      indentType = ' ';
    }
    if (lineIndent.amount) {
      indentAmount = indentAmount > lineIndent.amount ? lineIndent.amount : indentAmount;
    }
  }

  return lines.map((line) => {
    const lineIndent = repeating(indentAmount, indentType);

    const match = line.match(new RegExp(`(${lineIndent})`, 'g'));

    const indent = match ? match.join('') : ''

    line = line.replace(new RegExp(lineIndent, 'g'), '\t');

    return indent + JSON.stringify(line);
  }).join(',\n');
}

// console.log(getSnippet(`import subprocess
// hostname = subprocess.Popen("hostname",
//                     stdout=subprocess.PIPE).stdout.read().decode().strip()`.split('\n')))