#!/usr/bin/env python
import socket
from HTMLParser import HTMLParser
s = socket.socket()
s.connect(("www.smn.gov.ar",80))
s.send("GET /dpd/tiepre/tiepreMiguel.php?e=87344&amp;imagen=ZN HTTP /1.1\n\n")
rst = s.recv(1000000000)
rst += s.recv(1000000000)
# print rst

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
    	# if tag == "font":    		
        # 	print "Encountered a start tag:", tag
        pass
    def handle_endtag(self, tag):
    	pass
    	# if tag == "font":    		
        # 	print "Encountered an end tag :", tag
    def handle_data(self, data):
    	pass
    	if any(map(str.isalpha, data)):
        	print data

# instantiate the parser and fed it some HTML
parser = MyHTMLParser()
parser.feed(rst)